on:
  push:
    branches: ['release/**']

jobs:
  deployment:
    environment: production
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.8]
        poetry-version: [1.3.1]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Poetry & NPM dependencies
        run: make install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
